# Ruff configuration for bmd_videohub

line-length = 120

[lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
]
ignore = ["N802"]  # Allow non-lowercase function names for backward compatibility

[format]
# Use double quotes for strings
quote-style = "double"

# Unix-style line endings
line-ending = "lf"